apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-webapp
  template:
    metadata:
      labels:
        app: go-webapp
    spec:
      containers:
        - name: go-webapp
          image: europe-west6-docker.pkg.dev/playground-394421/astrafy-docker/go-webapp:IMAGE_TAG
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "20m"
              memory: "64Mi"
            requests:
              cpu: "10m"
              memory: "32Mi"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: go-webapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-webapp
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
---
apiVersion: v1
kind: Service
metadata:
  name: go-webapp-service
spec:
  selector:
    app: go-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
