name: CD - Deploy to GKE

on:
  workflow_dispatch:  # Allow manual triggering

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: europe-west6
  GKE_CLUSTER: playground-394421-gke
  GKE_ZONE: europe-west6-a
  DEPLOYMENT_NAME: go-webapp

jobs:
  deploy-to-gke:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/819195285046/locations/global/workloadIdentityPools/github/providers/github-provider'
        service_account: 'github-actions@playground-394421.iam.gserviceaccount.com'

    # Get the GKE credentials so we can deploy to the cluster
    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    # Update the Deployment YAML with the new image tag
    - name: Update Deployment YAML
      run: |
        sed -i "s|IMAGE_TAG|$GITHUB_SHA|g" deployment.yml

    # Deploy the application
    - name: Deploy
      run: |-
        kubectl apply -f deployment.yml
        kubectl rollout status deployment/${DEPLOYMENT_NAME}
        kubectl get services -o wide
